### ISSUE TITLE
Unable to download the project

### ISSUE THREAD

**Issue by EnockNitti** [kleydon/FIR-Filter-Demo-Cpp#1]
Unable to download the project

When I download the project as ZIP I get a 176 KB file.
But after unzipping I get a foldrer of 98 KB and I cant find any .cpp nor .hpp files.

Whats up ?

**Comment by kleydon** [comment]
Strange; I'm able to download it (at least the master branch) without problem.
If you happen to try again, and it still doesn't work, let me know.
