### ISSUE TITLE
AEC Filter

### ISSUE THREAD

**Issue by StuartIanNaylor** [kleydon/FIR-Filter-Demo-Cpp#2]
Maybe for the next project as opensource AI would really benefit from some new low load SoC based filter methods :)

**Comment by kleydon** [comment]
Interesting; I'd mainly been thinking of mobile, tablet and desktop ecosystems when I wrote this, but I can see how filters will play an increasingly interesting role on embedded devices... (Particularly now that machine learning techniques are starting to be accessible for SOCs!)

Thanks for the suggestion; I'll mull it over.

**Comment by StuartIanNaylor** [comment]
Yeah if you ever fancy a visit take a look at https://rhasspy.readthedocs.io/en/latest/ :)

I have been wondering for a while how optimised are the 2 main AEC routines for SoC and can they be improved but it takes some real lean code and far too much math for the likes of me.

Opensource is sort of locked out on various levels due to the better algs being harware or licence based.

Thanks for the reply.
Stuart
